// Build a conventional SAST "finding" model from an F2-A evidence package:
// header metadata + 개요(overview) + 데이터 흐름(taint trace) + 검사(checks) + 권고(remediation).
// Everything is generated by interpolating live analysis data — no per-example
// literals. Korean phrasing comes from small maps over the design's controlled
// enums (sink domain / check id / strength / status) with generic fallbacks.

import type {
  F2AResult,
  EvidencePackage,
  HandlerMap,
  HandlerResolution,
  HandlerResolutionCandidate,
} from "./types";

export interface TraceStep {
  n: number;
  line: number;
  fn: string;
  file: string;
  role: "source" | "step" | "sink";
  note: string;
}

export interface CheckRow {
  id: string;
  status: string; // raw code for colour: SATISFIED / UNVERIFIED / NEGATIVE / WEAKLY_RELATED
  observed?: string;
  evidence?: string;
}

export interface TraceNote {
  label: string; // user-facing label (e.g. "매칭 방식")
  value: string; // user-facing value (e.g. "식별자 정확 일치")
  hint: string; // tooltip: the raw implementation term / what it means
}

export interface Decision {
  id: string;
  kind: "vuln" | "handler"; // one result model, two result types
  hasFinding: boolean; // gates the vuln-only sections (checks / remediation / confidence factors)
  action: string;
  field: string;
  eyebrow: string; // small context label above the headline (handler: the OCPP action)
  subtitle: string; // action.field · semantic (vuln) | → handler() (handler)
  title: string; // plain-language conclusion headline (the meaning, not the backend status)
  verdict: string; // analysis-specific badge: 검토 후보 (vuln) | 핸들러 확인 / 복수 후보 / 판정 불가 (handler)
  tone: string; // vbadge tone: suspect | none | ok | warn | info (info = resolved, a non-security state)
  chipLabel: string; // label in the multi-result chip row
  component: string; // OCPP component (e.g. charge_point)
  ocppVersion: string;
  confidence: number;
  confidenceLabel: string;
  cwe: string[];
  location: string; // sink file:line
  overview: string;
  traceLabel: string; // "데이터 흐름" (vuln) | "판정 근거" (handler)
  trace: TraceStep[];
  traceNote: TraceNote[]; // supporting detail shown as a caption above the trace (handler)
  meta: [string, string][]; // header badge pairs (kept minimal — conclusions come first)
  checks: CheckRow[];
  confidenceFactors: [string, number][];
  remediation: string[];
  handlers: { action: string; fn: string }[];
  limitations: string[];
}

function koRecordType(t: string): string {
  return (
    {
      DISPATCH_STRING_MATCH: "문자열 디스패치",
      DISPATCH_ENUM_CASE: "enum/switch",
      DISPATCH_HANDLER_TABLE: "등록 테이블",
      DISPATCH_REGISTRAR_CALL: "등록 함수 호출",
      HANDLER_CALL: "핸들러 호출",
      HANDLER_REF: "핸들러",
      HANDLER_NAME_PATTERN: "이름 패턴",
      HANDLER_NAME_MATCH: "이름 매칭",
      ACTION_STORE: "액션 저장",
      FN_STORE: "핸들러 저장",
      SLOT: "슬롯",
      CHAIN_CALL: "위임 호출",
      CHAIN_STORE: "필드 저장",
    }[t] ?? t
  );
}

// Friendly renderings of F2-A implementation vocabulary, so a reader who did not
// build the pipeline can understand the result. Each keeps the raw term available
// as a tooltip (the `hint`) for auditability.
function koMatchStrength(s: string): string {
  return (
    {
      EXACT_IDENTIFIER: "식별자 정확 일치",
      NORMALIZED_IDENTIFIER: "정규화 후 일치",
      HEURISTIC_SUBSTRING: "부분 문자열(휴리스틱)",
      NAME_ONLY: "이름만 일치",
      NONE: "일치 없음",
    }[s] ?? s
  );
}

function koConsistency(s: string): string {
  return { CONSISTENT: "일관됨", PARTIAL: "부분 일치", CONFLICTING: "상충" }[s] ?? s;
}

function koEvidenceKind(s: string): string {
  return (
    {
      STRING_DISPATCH: "문자열 디스패치",
      ENUM_CASE: "enum/switch 분기",
      REGISTRATION_INIT: "등록 테이블 초기화",
      REGISTRATION_ASSIGN: "등록 테이블 대입",
      REGISTRAR_CALL: "등록 함수 호출",
      NAME_MATCH: "이름 매칭",
      DISPATCH_SITE: "디스패치 지점",
    }[s] ?? s
  );
}

function koReason(s: string): string {
  return (
    {
      NO_EVIDENCE: "근거 없음",
      LOW_CONFIDENCE: "신뢰도 부족",
      UNSUPPORTED_REGISTRAR_CALL: "지원하지 않는 등록 함수 호출",
      REGISTRAR_STORE_NOT_REACHED: "등록 함수는 인식했지만 액션→슬롯 연결을 확인하지 못함",
      REGISTRAR_SEARCH_THEN_WRITE:
        "등록 함수가 반복문+조건으로 슬롯을 런타임에 탐색해 콜백만 저장하는 방식(search-then-write)이라, 현재 분석 범위 밖입니다",
      UNRESOLVED_INDIRECT_CALL: "간접 호출을 해석하지 못함",
      EXTERNAL_DEFINITION: "외부에 정의된 핸들러",
      DYNAMIC_ACTION_ID: "동적으로 결정되는 액션 식별자",
      MISSING_POINTSTO: "포인터 분석 정보 부족",
      GENERATED_CODE_UNAVAILABLE: "생성 코드가 없어 분석 불가",
      REGISTRATION_OUT_OF_TU: "번역 단위 밖에서 등록됨",
    }[s] ?? s
  );
}

function koExtractor(s: string): string {
  return (
    {
      name_match: "이름 매칭",
      registration_ast: "등록 테이블 분석",
      registrar_call: "등록 함수 추적",
      string_dispatch: "문자열 디스패치 분석",
      enum_case: "enum/switch 분석",
    }[s] ?? s
  );
}

function num(x: unknown): number {
  if (typeof x === "number") return x;
  const n = parseInt(String(x), 10);
  return Number.isFinite(n) ? n : NaN;
}

export function koConfidence(v: number): string {
  if (v >= 0.8) return "높음";
  if (v >= 0.6) return "보통";
  if (v >= 0.4) return "낮지만 검토 가능";
  return "낮음";
}

export function koStrength(s: string): string {
  return { STRONG: "강함", PARTIAL: "부분", WEAK: "약함", UNKNOWN: "불명", CONFLICTED: "상충" }[s] ?? s;
}

export function koStatus(s: string): string {
  return (
    {
      SATISFIED: "충족",
      PARTIALLY_SATISFIED: "부분 충족",
      WEAKLY_RELATED: "약하게 관련",
      UNVERIFIED: "미확인",
      NEGATIVE: "우회",
      NEGATIVE_EVIDENCE_FOUND: "우회",
      CONFLICTED: "상충",
      REVIEW_REQUIRED: "검토 필요",
    }[s] ?? s
  );
}

function domainNoun(d: string): string {
  return (
    {
      COMMAND_EXECUTION: "명령 실행",
      UNSAFE_FIRMWARE_DOWNLOAD: "펌웨어 다운로드",
      UNSAFE_EXTERNAL_RESOURCE: "외부 리소스 접근",
      MEMORY_UNSAFE_OPERATION: "메모리 쓰기",
      FILE_WRITE: "파일 쓰기",
      REMOTE_COMMAND_DISPATCH: "원격 명령",
      AUTHORIZATION_DECISION: "인가 결정",
    }[d] ?? d
  );
}

function remediationFor(checkId: string): string {
  return (
    {
      URL_SCHEME_VALIDATION: "다운로드 URL의 스킴을 https 로 제한하고 검증하세요.",
      HOST_ALLOWLIST: "다운로드 호스트를 허용 목록(allowlist)으로 제한하세요.",
      SIGNATURE_VERIFICATION: "설치 전에 펌웨어 서명을 검증하세요.",
      SAFE_DOWNLOAD_API_NO_SHELL: "system()/셸 대신 안전한 다운로드 API(예: libcurl)를 사용하세요.",
      OPERATOR_PERMISSION_CHECK: "동작을 수행하기 전에 운영자 권한을 확인하세요.",
      HOST_ALLOWLIST_CHECK: "요청 호스트를 허용 목록으로 제한하세요.",
    }[checkId] ?? `${checkId} 검사를 추가하세요.`
  );
}

function buildOne(pkg: EvidencePackage, handlers: HandlerMap[]): Decision {
  const ctx = pkg.ocpp_context;
  const ce = pkg.code_evidence;
  const sink = ce.sink;
  const conf = pkg.static_confidence;
  const dNoun = domainNoun(sink.sink_domain);

  const flowFns = Array.from(new Set(ce.flow.map((s) => s.function)));
  const crossed = flowFns.length;

  const trace: TraceStep[] = ce.flow.map((s, i) => {
    const isSink = s.operation.startsWith("sink");
    return {
      n: i + 1,
      line: num(s.line),
      fn: s.function,
      file: s.file,
      role: i === 0 ? "source" : isSink ? "sink" : "step",
      note:
        i === 0
          ? `소스 · ${ctx.field}`
          : isSink
            ? `싱크 · ${dNoun}`
            : s.operation.replace("argument_pass ", "인자 전달 "),
    };
  });

  const missing = pkg.check_evidence.missing_check_candidates;
  const observed = pkg.check_evidence.observed_checks;
  const checks: CheckRow[] = pkg.check_evidence.expected_checks.map((ec) => {
    const m = missing.find((x) => x.check_id === ec);
    const obs = observed.find((o) => o.matched_expected_check === ec);
    let status = "SATISFIED";
    if (m) status = m.basis === "NEGATIVE_EVIDENCE_FOUND" ? "NEGATIVE" : m.basis;
    return {
      id: ec,
      status,
      observed: obs ? `${obs.check_type} · ${koStrength(obs.check_strength)}` : undefined,
      evidence: obs?.evidence,
    };
  });
  // add observed checks that don't map to an expected one (e.g. weak NULL_CHECK)
  for (const o of observed) {
    if (!o.matched_expected_check) {
      checks.push({
        id: o.check_type,
        status: o.check_strength === "STRONG" ? "SATISFIED" : "WEAKLY_RELATED",
        observed: `${o.check_type} · ${koStrength(o.check_strength)}`,
        evidence: o.evidence,
      });
    }
  }

  const remediation = Array.from(
    new Set(missing.map((m) => remediationFor(m.check_id))),
  );

  const overview =
    `${ctx.action} 요청의 “${ctx.field}” 필드(${ctx.field_semantic})는 외부에서 조작 가능한 신뢰할 수 없는 입력이며, ` +
    `${crossed > 1 ? `함수 ${crossed}개를 거쳐 ` : ""}${sink.api}() (${dNoun}) 까지 충분한 검증 없이 도달합니다.`;

  return {
    id: pkg.evidence_id,
    kind: "vuln",
    hasFinding: true,
    action: ctx.action,
    field: ctx.field,
    eyebrow: "",
    subtitle: `${ctx.action}.${ctx.field} · ${ctx.field_semantic}`,
    title: `외부 입력이 ${sink.api}() (${dNoun}) 싱크까지 도달합니다`,
    verdict: "검토 후보",
    tone: "suspect",
    chipLabel: `${ctx.action}.${ctx.field}`,
    component: pkg.component_type,
    ocppVersion: ctx.ocpp_version,
    confidence: conf,
    confidenceLabel: koConfidence(conf),
    cwe: pkg.related_cwe,
    location: `${sink.file}:${sink.line}`,
    overview,
    traceLabel: "데이터 흐름",
    trace,
    traceNote: [],
    meta: [],
    checks,
    confidenceFactors: [
      ["handler", pkg.confidence.handler_mapping],
      ["field", pkg.confidence.field_binding],
      ["semantic", pkg.confidence.semantic_binding],
      ["flow", pkg.confidence.source_sink_flow],
      ["sink", pkg.confidence.sink_mapping],
      ["checks", pkg.confidence.check_detection],
      ["trace", pkg.confidence.traceability],
    ],
    remediation,
    handlers: handlers.map((h) => ({ action: h.action, fn: h.handler.function })),
    limitations: pkg.limitations,
  };
}

function traceFromCandidate(c: HandlerResolutionCandidate): TraceStep[] {
  const recs = (c.evidence ?? []).flatMap((e) => e.records);
  return recs.map((rec, i) => ({
    n: i + 1,
    line: num(rec.line),
    fn: koRecordType(rec.type),
    file: rec.file,
    role: rec.type === "HANDLER_REF" ? "sink" : i === 0 ? "source" : "step",
    note: rec.value,
  }));
}

// Analysis-specific status vocabulary. `tone` deliberately avoids ok(green) /
// suspect(red): a resolved handler is not a security "pass", so it reads blue
// (info); green/red stay reserved for actual security findings.
const STATUS_META: Record<string, { tone: string; verdict: string; title: string }> = {
  RESOLVED: { tone: "info", verdict: "핸들러 확인", title: "핸들러를 확인했습니다" },
  AMBIGUOUS: { tone: "warn", verdict: "복수 후보", title: "핸들러 후보가 여러 개입니다" },
  UNRESOLVED: { tone: "none", verdict: "판정 불가", title: "핸들러를 확정하지 못했습니다" },
};

function evidenceNotes(cand: HandlerResolutionCandidate | undefined): TraceNote[] {
  const e0 = cand?.evidence?.[0];
  if (!e0) return [];
  const notes: TraceNote[] = [
    { label: "판정 방식", value: koEvidenceKind(e0.kind), hint: e0.kind },
    { label: "매칭 방식", value: koMatchStrength(e0.match_strength), hint: e0.match_strength },
    {
      label: "식별자 일관성",
      value: koConsistency(e0.action_id_consistency),
      hint: `${e0.action_id_consistency} — 액션 식별자가 등록/디스패치 지점과 얼마나 일치하는지`,
    },
    {
      label: "근거 점수",
      value: `${e0.score_pre_penalty.toFixed(2)} → ${e0.score.toFixed(2)}`,
      hint: "패널티 적용 전 → 적용 후 (근거의 연결 강도이며, 보안 심각도가 아님)",
    },
  ];
  return notes;
}

function handlerDecision(
  hr: HandlerResolution,
  cand: HandlerResolutionCandidate | undefined,
  idx: number,
  n: number,
  limitations: string[],
): Decision {
  const sm = STATUS_META[hr.status] ?? STATUS_META.UNRESOLVED;
  const conf = cand?.confidence ?? 0;

  // Lead with the conclusion (the meaning), not the backend status code.
  let title = sm.title;
  let subtitle = cand ? `→ ${cand.function}()` : "";
  let overview: string;
  const traceNote = evidenceNotes(cand);

  if (hr.status === "RESOLVED" && cand) {
    overview =
      `${hr.action} 액션은 코드에서 핸들러 함수 ${cand.function}() 로 연결됩니다. ` +
      `아래 근거가 이 매핑을 뒷받침합니다.`;
  } else if (hr.status === "AMBIGUOUS" && cand) {
    title = `${sm.title} (후보 ${idx + 1}/${n})`;
    subtitle = `후보 ${idx + 1}/${n} · → ${cand.function}()`;
    overview =
      `${hr.action} 액션에 대해 여러 핸들러 후보가 비슷한 강도로 경합하여, ` +
      `자동으로 하나를 선택하지 않았습니다. 각 후보의 근거를 나란히 확인하세요.`;
    if (hr.conflict) {
      traceNote.unshift({
        label: "이 후보 신뢰도",
        value: conf.toFixed(2),
        hint: "이 후보 근거의 연결 강도 (보안 심각도가 아님)",
      });
      traceNote.push({
        label: "상위 후보 점수차",
        value: hr.conflict.margin.toFixed(2),
        hint: "1·2위 후보의 점수 차이 — 작을수록 더 모호합니다",
      });
    }
  } else {
    const u = hr.unresolved;
    const rawReason = u?.reason ?? "NO_EVIDENCE";
    subtitle = `사유 · ${koReason(rawReason)}`;
    const tried = (u?.attempted_extractors ?? []).map(koExtractor).join(", ");
    overview =
      `${hr.action} 액션의 핸들러를 코드에서 찾지 못했습니다. ` +
      `사유: ${koReason(rawReason)} (${rawReason}).` +
      (u?.secondary ? ` 부가 사유: ${koReason(u.secondary)}.` : "") +
      (tried ? ` 시도한 분석: ${tried}.` : "");
  }

  return {
    id: `${hr.action}:${cand?.function ?? hr.status}:${idx}`,
    kind: "handler",
    hasFinding: false,
    action: hr.action,
    field: "",
    eyebrow: hr.action,
    subtitle,
    title,
    verdict: sm.verdict,
    tone: sm.tone,
    chipLabel: hr.status === "AMBIGUOUS" && cand ? `${hr.action} · ${cand.function}` : hr.action,
    component: "",
    ocppVersion: "",
    // Confidence supports the conclusion; it is not the headline. Shown only for a
    // single resolved handler, where a single number is meaningful.
    confidence: hr.status === "RESOLVED" ? conf : 0,
    confidenceLabel: hr.status === "RESOLVED" ? koConfidence(conf) : "",
    cwe: [],
    location: cand ? `${cand.file}:${cand.line}` : "",
    overview,
    traceLabel: "판정 근거",
    trace: cand ? traceFromCandidate(cand) : [],
    traceNote,
    meta: [], // header stays conclusion-first; detail lives in traceNote
    checks: [],
    confidenceFactors: [],
    remediation: [],
    handlers: [],
    limitations,
  };
}

function noFinding(result: F2AResult): Decision {
  return {
    id: "none",
    kind: "vuln",
    hasFinding: false,
    action: "",
    field: "",
    eyebrow: "",
    subtitle: "",
    title: "신뢰할 수 없는 입력 → 위험 싱크 경로를 찾지 못했습니다",
    verdict: "발견 없음",
    tone: "none",
    chipLabel: "결과",
    component: "",
    ocppVersion: "",
    confidence: 0,
    confidenceLabel: "",
    cwe: [],
    location: "",
    overview: "이 코드에서 위험한 싱크에 도달하는 OCPP 페이로드 필드를 찾지 못했습니다.",
    traceLabel: "데이터 흐름",
    trace: [],
    traceNote: [],
    meta: [],
    checks: [],
    confidenceFactors: [],
    remediation: [],
    handlers: result.handler_maps.map((h) => ({ action: h.action, fn: h.handler.function })),
    limitations: result.limitations,
  };
}

export function buildDecisions(result: F2AResult): Decision[] {
  if (result.evidence_packages.length > 0) {
    return result.evidence_packages.map((p) => buildOne(p, result.handler_maps));
  }

  // No source→sink finding: render the handler resolutions through the SAME
  // result model (one card per action; per-candidate for AMBIGUOUS).
  const resolutions = result.handler_resolutions ?? [];
  if (resolutions.length > 0) {
    const order: Record<string, number> = { RESOLVED: 0, AMBIGUOUS: 1, UNRESOLVED: 2 };
    const sorted = [...resolutions].sort(
      (a, b) => (order[a.status] ?? 9) - (order[b.status] ?? 9) || a.action.localeCompare(b.action),
    );
    const out: Decision[] = [];
    for (const hr of sorted) {
      if (hr.status === "AMBIGUOUS" && hr.candidates.length > 0) {
        hr.candidates.forEach((c, i) =>
          out.push(handlerDecision(hr, c, i, hr.candidates.length, result.limitations)),
        );
      } else {
        out.push(handlerDecision(hr, hr.candidates[0], 0, hr.candidates.length, result.limitations));
      }
    }
    if (out.length) return out;
  }
  return [noFinding(result)];
}
