"""Node type definitions and unions."""

from typing import List, Union

from .template import (
    IAddressOfExpression,
    IArrayDeclaration,
    IArraySizeAllocation,
    IArraySubscriptExpression,
    IAssignmentExpression,
    IBaseNode,
    IBinaryExpression,
    IBreakStatement,
    ICaseLabel,
    ICastExpression,
    ICompoundStatement,
    IContinueStatement,
    IDefaultLabel,
    IDoWhileStatement,
    IEnumType,
    IForStatement,
    IFunctionDeclaration,
    IFunctionDefinition,
    IGotoStatement,
    IIdentifier,
    IIfStatement,
    IIncludeDirective,
    ILabel,
    ILiteral,
    IMacroDefinition,
    IMemberAccess,
    IParameterDeclaration,
    IParameterList,
    IPointerDeclaration,
    IPointerDereference,
    IReturnStatement,
    ISizeOfExpression,
    IStandardLibCall,
    IStructType,
    ISwitchStatement,
    ITranslationUnit,
    ITypeDefinition,
    IUnaryExpression,
    IUnionType,
    IUserDefinedCall,
    IVariableDeclaration,
    IWhileStatement,
    TemplateFlattenedGraph,
    TemplateFlattenedNode,
    TemplateNodeTypes,
)

# Union type of all possible template nodes
TemplateNodes = Union[
    IBaseNode,
    ICompoundStatement,
    IBreakStatement,
    ICaseLabel,
    IContinueStatement,
    IDefaultLabel,
    IDoWhileStatement,
    IForStatement,
    IGotoStatement,
    IIfStatement,
    ILabel,
    IReturnStatement,
    ISwitchStatement,
    IWhileStatement,
    IEnumType,
    IStructType,
    ITypeDefinition,
    IUnionType,
    IAddressOfExpression,
    IArraySizeAllocation,
    IArraySubscriptExpression,
    IAssignmentExpression,
    IBinaryExpression,
    ICastExpression,
    IIdentifier,
    ILiteral,
    IMemberAccess,
    IPointerDereference,
    ISizeOfExpression,
    IStandardLibCall,
    IUnaryExpression,
    IUserDefinedCall,
    IIncludeDirective,
    IMacroDefinition,
    IArrayDeclaration,
    IFunctionDeclaration,
    IFunctionDefinition,
    IParameterDeclaration,
    IParameterList,
    IPointerDeclaration,
    ITranslationUnit,
    IVariableDeclaration,
]

__all__ = [
    "TemplateNodes",
    "TemplateFlattenedNode",
    "TemplateFlattenedGraph",
    "TemplateNodeTypes",
    "IBaseNode",
]


