version: '3.9'
services:
  db:
    image: postgres:16
    container_name: ssat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?Set up POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set up POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:?Set up POSTGRES_DB}
    ports:
      - '${DB_PORT:?Set up DB_PORT}:5432'
    volumes:
      - ssat_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  ssat_pg_data:
