from typing import Dict, List, TypedDict

from typing import Union

from .BaseNode.base_types import IBaseNode, TemplateNodeTypes
from .blocks import ICompoundStatement
from .control_structures import (
    IBreakStatement,
    ICaseLabel,
    IContinueStatement,
    IDefaultLabel,
    IDoWhileStatement,
    IForStatement,
    IGotoStatement,
    IIfStatement,
    ILabel,
    IReturnStatement,
    ISwitchStatement,
    IWhileStatement,
)
from .data_types import IEnumType, IStructType, ITypeDefinition, IUnionType
from .expressions import (
    IAddressOfExpression,
    IArraySizeAllocation,
    IArraySubscriptExpression,
    IAssignmentExpression,
    IBinaryExpression,
    ICastExpression,
    IIdentifier,
    ILiteral,
    IMemberAccess,
    IPointerDereference,
    ISizeOfExpression,
    IStandardLibCall,
    IUnaryExpression,
    IUserDefinedCall,
)
from .preprocessor_directives import IIncludeDirective, IMacroDefinition
from .program_structures import (
    IArrayDeclaration,
    IFunctionDeclaration,
    IFunctionDefinition,
    IParameterDeclaration,
    IParameterList,
    IPointerDeclaration,
    ITranslationUnit,
    IVariableDeclaration,
)

TemplateNodes = Union[
    IBaseNode,
    ICompoundStatement,
    IBreakStatement,
    ICaseLabel,
    IContinueStatement,
    IDefaultLabel,
    IDoWhileStatement,
    IForStatement,
    IGotoStatement,
    IIfStatement,
    ILabel,
    IReturnStatement,
    ISwitchStatement,
    IWhileStatement,
    IEnumType,
    IStructType,
    ITypeDefinition,
    IUnionType,
    IAddressOfExpression,
    IArraySizeAllocation,
    IArraySubscriptExpression,
    IAssignmentExpression,
    IBinaryExpression,
    ICastExpression,
    IIdentifier,
    ILiteral,
    IMemberAccess,
    IPointerDereference,
    ISizeOfExpression,
    IStandardLibCall,
    IUnaryExpression,
    IUserDefinedCall,
    IIncludeDirective,
    IMacroDefinition,
    IArrayDeclaration,
    IFunctionDeclaration,
    IFunctionDefinition,
    IParameterDeclaration,
    IParameterList,
    IPointerDeclaration,
    ITranslationUnit,
    IVariableDeclaration,
]


class TemplateFlattenedGraph(TypedDict):
    edges: List[Dict[str, int]]
    nodes: List["TemplateNodes"]


__all__ = [
    "TemplateNodeTypes",
    "IBaseNode",
    "TemplateNodes",
    "TemplateFlattenedGraph",
    "IAddressOfExpression",
    "IArraySizeAllocation",
    "IArraySubscriptExpression",
    "IAssignmentExpression",
    "IBinaryExpression",
    "ICastExpression",
    "IIdentifier",
    "ILiteral",
    "IMemberAccess",
    "IPointerDereference",
    "ISizeOfExpression",
    "IStandardLibCall",
    "IUnaryExpression",
    "IUserDefinedCall",
    "ICompoundStatement",
    "IBreakStatement",
    "ICaseLabel",
    "IContinueStatement",
    "IDefaultLabel",
    "IDoWhileStatement",
    "IForStatement",
    "IGotoStatement",
    "IIfStatement",
    "ILabel",
    "IReturnStatement",
    "ISwitchStatement",
    "IWhileStatement",
    "IEnumType",
    "IStructType",
    "ITypeDefinition",
    "IUnionType",
    "IIncludeDirective",
    "IMacroDefinition",
    "IArrayDeclaration",
    "IFunctionDeclaration",
    "IFunctionDefinition",
    "IParameterDeclaration",
    "IParameterList",
    "IPointerDeclaration",
    "ITranslationUnit",
    "IVariableDeclaration",
]
