from typing import Dict

CALL_SEM_ID = {
    "none": 0,
    "mem_alloc": 1,
    "mem_copy": 2,
    "ext_input": 3,
    "format_print": 4,
    "mem_set": 5,
    "net_connect": 6,
    "net_close": 7,
    "socket_create": 8,
    "parse_int_unchecked": 9,
    "parse_int_checked": 10,
}

CALL_PRIORITY = [
    "none",
    "mem_alloc",
    "mem_copy",
    "ext_input",
    "format_print",
    "mem_set",
    "net_connect",
    "net_close",
    "socket_create",
    "parse_int_unchecked",
    "parse_int_checked",
]


CALL_SEM = {
    "mem_alloc": {
        "malloc",
        "calloc",
        "realloc",
        "xmalloc",
        "xcalloc",
        "xrealloc",
        "valloc",
        "memalign",
        "HeapAlloc",
        "HeapReAlloc",
        "HeapCreate",
        "new",
        "new[]",
        "alloca",
        "ALLOCA",
        "_alloca",
    },
    "mem_copy": {
        "memcpy",
        "memmove",
        "memcpy_s",
        "memmove_s",
        "bcopy",
        "CopyMemory",
        "RtlCopyMemory",
        "wmemcpy",
        "wmemmove",
        "wmemcpy_s",
        "wmemmove_s",
        "strcpy",
        "strcpy_s",
        "strncpy",
        "strncpy_s",
        "wcscpy",
        "wcscpy_s",
        "wcsncpy",
        "wcsncpy_s",
        "lstrcpy",
        "lstrcpyn",
        "StrCpy",
        "StrCpyN",
        "StrCpyNW",
        "strcat",
        "strcat_s",
        "strncat",
        "strncat_s",
        "wcscat",
        "wcscat_s",
        "wcsncat",
        "wcsncat_s",
        "lstrcat",
        "StrCat",
        "StrCatN",
        "StrCatNW",
    },
    "ext_input": {
        "gets",
        "gets_s",
        "fgets",
        "getline",
        "scanf",
        "sscanf",
        "fscanf",
        "scanf_s",
        "sscanf_s",
        "fscanf_s",
        "wscanf",
        "swscanf",
        "fwscanf",
        "wscanf_s",
        "swscanf_s",
        "fwscanf_s",
        "read",
        "pread",
        "pread64",
        "fread",
        "recv",
        "recvfrom",
    },
    "format_print": {
        "printf",
        "fprintf",
        "vprintf",
        "vfprintf",
        "puts",
        "printIntLine",
        "sprintf",
        "vsprintf",
        "snprintf",
        "vsnprintf",
        "sprintf_s",
        "vsprintf_s",
        "_snprintf",
        "_vsnprintf",
        "_snwprintf",
        "_vsntprintf",
        "swprintf",
        "vswprintf",
        "vswprintf_s",
        "wsprintf",
        "wvsprintf",
        "wnsprintf",
        "wvnsprintf",
    },
    "mem_set": {"memset", "bzero", "wmemset", "RtlZeroMemory"},
    "net_connect": {"connect"},
    "net_close": {"closesocket", "close", "close_socket", "CLOSE_SOCKET"},
    "socket_create": {"socket", "WSASocket", "wsasocket"},
    "parse_int_unchecked": {"atoi", "atol", "atoll", "_atoi64"},
    "parse_int_checked": {
        "strtol",
        "strtoul",
        "strtoll",
        "strtoull",
        "strtoimax",
        "strtoumax",
        "wcstol",
        "wcstoul",
        "wcstoll",
        "wcstoull",
        "wcstoimax",
        "wcstoumax",
    },
}


CALL_SEM_MAP: Dict[str, int] = {}
for cat in CALL_PRIORITY:
    cid = CALL_SEM_ID[cat]
    for nm in CALL_SEM.get(cat, ()):
        CALL_SEM_MAP.setdefault(nm.lower(), cid)


def call_sem_cat_id_from_name(name: str) -> int:
    return int(CALL_SEM_MAP.get((name or "").lower(), 0))


UNBOUNDED_CALLS = {
    "gets",
    "strcpy",
    "strcat",
    "sprintf",
    "vsprintf",
    "_getws",
    "getwd",
    "wcscpy",
    "wcscat",
    "lstrcpy",
    "lstrcat",
    "stpcpy",
    "wcpcpy",
    "_mbscpy",
    "_mbscat",
    "wsprintf",
    "wvsprintf",
}

API_SLOTS = {
    "memset": {"dst": 0, "size": 2},
    "bzero": {"dst": 0, "size": 1},
    "wmemset": {"dst": 0, "size": 2},
    "rtlzeromemory": {"dst": 0, "size": 1},
    "memcpy": {"dst": 0, "size": 2},
    "memcpy_s": {"dst": 0, "size": 3},
    "memmove": {"dst": 0, "size": 2},
    "memmove_s": {"dst": 0, "size": 3},
    "bcopy": {"dst": 1, "size": 2},
    "copymemory": {"dst": 0, "size": 2},
    "rtlcopymemory": {"dst": 0, "size": 2},
    "wmemcpy": {"dst": 0, "size": 2},
    "wmemcpy_s": {"dst": 0, "size": 3},
    "wmemmove": {"dst": 0, "size": 2},
    "wmemmove_s": {"dst": 0, "size": 3},
    "strcpy": {"dst": 0, "size": None},
    "strcpy_s": {"dst": 0, "size": 1},
    "strncpy": {"dst": 0, "size": 2},
    "strncpy_s": {"dst": 0, "size": 3},
    "wcscpy": {"dst": 0, "size": None},
    "wcscpy_s": {"dst": 0, "size": 1},
    "wcsncpy": {"dst": 0, "size": 2},
    "wcsncpy_s": {"dst": 0, "size": 3},
    "lstrcpy": {"dst": 0, "size": None},
    "lstrcpyn": {"dst": 0, "size": 2},
    "strcpyn": {"dst": 0, "size": 2},
    "strcpynw": {"dst": 0, "size": 2},
    "strcat": {"dst": 0, "size": None},
    "strcat_s": {"dst": 0, "size": 1},
    "strncat": {"dst": 0, "size": 2},
    "strncat_s": {"dst": 0, "size": 3},
    "wcscat": {"dst": 0, "size": None},
    "wcscat_s": {"dst": 0, "size": 1},
    "wcsncat": {"dst": 0, "size": 2},
    "wcsncat_s": {"dst": 0, "size": 3},
    "lstrcat": {"dst": 0, "size": None},
    "strcatn": {"dst": 0, "size": 2},
    "strcatnw": {"dst": 0, "size": 2},
    "gets": {"dst": 0, "size": None},
    "gets_s": {"dst": 0, "size": 1},
    "fgets": {"dst": 0, "size": 1},
    "getline": {"dst": None, "size": None},
    "scanf": {"dst": None, "size": None},
    "sscanf": {"dst": None, "size": None},
    "fscanf": {"dst": None, "size": None},
    "scanf_s": {"dst": None, "size": None},
    "sscanf_s": {"dst": None, "size": None},
    "fscanf_s": {"dst": None, "size": None},
    "wscanf": {"dst": None, "size": None},
    "swscanf": {"dst": None, "size": None},
    "fwscanf": {"dst": None, "size": None},
    "wscanf_s": {"dst": None, "size": None},
    "swscanf_s": {"dst": None, "size": None},
    "fwscanf_s": {"dst": None, "size": None},
    "read": {"dst": 1, "size": 2},
    "pread": {"dst": 1, "size": 2},
    "pread64": {"dst": 1, "size": 2},
    "fread": {"dst": 0, "size": 2},
    "recv": {"dst": 1, "size": 2},
    "recvfrom": {"dst": 1, "size": 2},
    "sprintf": {"dst": 0, "size": None},
    "vsprintf": {"dst": 0, "size": None},
    "snprintf": {"dst": 0, "size": 1},
    "vsnprintf": {"dst": 0, "size": 1},
    "_snprintf": {"dst": 0, "size": 1},
    "_vsnprintf": {"dst": 0, "size": 1},
    "_snwprintf": {"dst": 0, "size": 1},
    "_vsntprintf": {"dst": 0, "size": 1},
    "swprintf": {"dst": 0, "size": 1},
    "vswprintf": {"dst": 0, "size": 1},
    "vswprintf_s": {"dst": 0, "size": 1},
    "wsprintf": {"dst": 0, "size": None},
    "wvsprintf": {"dst": 0, "size": None},
    "wnsprintf": {"dst": 0, "size": 1},
    "wvnsprintf": {"dst": 0, "size": 1},
    "connect": {"dst": 1, "size": 2},
    "closesocket": {"dst": None, "size": None},
    "close": {"dst": None, "size": None},
    "close_socket": {"dst": None, "size": None},
    "socket": {"dst": None, "size": None},
    "wsasocket": {"dst": None, "size": None},
    "atoi": {"dst": None, "size": None},
    "atol": {"dst": None, "size": None},
    "atoll": {"dst": None, "size": None},
    "_atoi64": {"dst": None, "size": None},
    "strtol": {"dst": None, "size": None},
    "strtoul": {"dst": None, "size": None},
    "strtoll": {"dst": None, "size": None},
    "strtoull": {"dst": None, "size": None},
    "strtoimax": {"dst": None, "size": None},
    "strtoumax": {"dst": None, "size": None},
    "wcstol": {"dst": None, "size": None},
    "wcstoul": {"dst": None, "size": None},
    "wcstoll": {"dst": None, "size": None},
    "wcstoull": {"dst": None, "size": None},
    "wcstoimax": {"dst": None, "size": None},
    "wcstoumax": {"dst": None, "size": None},
}


MEM_ALLOC_FUNCS_LOWER = {"malloc", "calloc", "realloc", "alloca", "_alloca"}
MEM_ALLOC_FUNCS_RAW = {"ALLOCA", "new[]"}


UNBOUNDED = {"gets", "strcpy", "strcat", "sprintf", "vsprintf"}
STD_FUNCTIONS = set().union(*CALL_SEM.values(), UNBOUNDED)


BOUNDED = {
    "memcpy",
    "memmove",
    "strncpy",
    "snprintf",
    "vsnprintf",
    "fgets",
    "read",
    "recv",
    "getline",
}


DFG_SINK_SLOTS: Dict[str, Dict[str, int | None]] = {
    "fgets": {"dst": 0, "size": 1},
    "gets": {"dst": 0, "size": None},
    "memcpy": {"dst": 0, "size": 2},
    "memmove": {"dst": 0, "size": 2},
    "strncpy": {"dst": 0, "size": 2},
    "snprintf": {"dst": 0, "size": 1},
    "vsnprintf": {"dst": 0, "size": 1},
    "strcpy": {"dst": 0, "size": None},
    "strcat": {"dst": 0, "size": None},
    "sprintf": {"dst": 0, "size": None},
    "vsprintf": {"dst": 0, "size": None},
    "read": {"dst": 1, "size": 2},
    "recv": {"dst": 1, "size": 2},
    "getline": {"dst": 0, "size": 1},
    "memset": {"dst": 0, "size": 2},
    "connect": {"dst": None, "size": 2},
}


def dfg_sink_slots(name: str) -> Dict[str, int | None]:
    return DFG_SINK_SLOTS.get(name, {})


AST_FLAG_SLOTS: Dict[str, Dict[str, int]] = {
    "memcpy": {"dst": 0, "size": 2, "argc": 3},
    "memmove": {"dst": 0, "size": 2, "argc": 3},
    "strncpy": {"dst": 0, "size": 2, "argc": 3},
    "memset": {"dst": 0, "size": 2, "argc": 3},
    "snprintf": {"dst": 0, "size": 1, "argc": 2},
    "vsnprintf": {"dst": 0, "size": 1, "argc": 2},
    "fgets": {"dst": 0, "size": 1, "argc": 2},
    "read": {"dst": 1, "size": 2, "argc": 3},
    "recv": {"dst": 1, "size": 2, "argc": 3},
    "connect": {"dst": 1, "size": 2, "argc": 3},
}


VARARGS_CALLS = frozenset({"printf", "fprintf", "vprintf", "vfprintf", "sprintf", "snprintf", "vsprintf", "vsnprintf"})


ALLOC_CALLS_FOR_SIZEOF = frozenset({"malloc", "calloc", "realloc", "alloca", "_alloca", "ALLOCA", "new", "new[]"})
